ViewModels/TenantViewModel.cs
using RentierApplication.Data.Entities;
using System.ComponentModel.DataAnnotations.Schema;

namespace RentierApplication.ViewModels
{
    public class TenantViewModel
    {        
        public int ID { get; set; }
        
        public string Name { get; set; }
        public string Surname { get; set; }

        public string Email { get; set; }

        public decimal MoneyObligation { get; set; }
        public decimal Surety { get; set; }
       
        public int RealEstateID { get; set; }        
    }
}

Controllers/PaymentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RentierApplication.DAL.Entities;
using RentierApplication.Data;
using RentierApplication.ViewModels;

namespace RentierApplication.Controllers
{
    //create route attribute or this controller

    public class PaymentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PaymentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Payments

        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Payments.Include(p => p.RealEstate);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Payments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Payments == null)
            {
                return NotFound();
            }

            var payment = await _context.Payments
                .Include(p => p.RealEstate)
                .Include(p => p.Transactions)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (payment == null)
            {
                return NotFound();
            }

            return View(payment);
        }

        // GET: Payments/Create
        public IActionResult Create()
        {
            ViewData["RealEstateId"] = new SelectList(_context.RealEstates, "ID", "Name");
            return View();
        }

        // POST: Payments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PaymentCreateViewModel paymentToAdd)
        {
            var payment = new Payment()
            {
                Id = paymentToAdd.Id,
                RealEstateId = paymentToAdd.RealEstateId,
                MonthlyIncome = paymentToAdd.MonthlyIncome,
            };

            _context.Add(payment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

            ViewData["RealEstateId"] = new SelectList(_context.RealEstates, "ID", "Name", payment.RealEstateId);
            return View();
        }

        // GET: Payments/Edit/5

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Payments == null)
            {
                return NotFound();
            }

            var payment = await _context.Payments.FindAsync(id);
            if (payment == null)
            {
                return NotFound();
            }
            ViewData["RealEstateId"] = new SelectList(_context.RealEstates, "ID", "Name", payment.RealEstateId);
            return View(payment);
        }

        // POST: Payments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, PaymentEditViewModel paymentToEdit)
        {
            var existingPayment = await _context.Payments.FindAsync(id);

            existingPayment.MonthlyIncome = paymentToEdit.MonthlyIncome;

            if (id != existingPayment.Id)
            {
                return NotFound();
            }

            await _context.SaveChangesAsync();

            if (!PaymentExists(existingPayment.Id))
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));

            ViewData["RealEstateId"] = new SelectList(_context.RealEstates, "ID", "Name", existingPayment.RealEstateId);
            return View(existingPayment);
        }

        // GET: Payments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var payment = await _context.Payments
                .Include(p => p.RealEstate)
                .FirstOrDefaultAsync(m => m.Id == id);

            PaymentDeleteViewModel paymentToDelete = new PaymentDeleteViewModel()
            {
                Id = payment.Id,
                RealEstateId = payment.RealEstateId,
                MonthlyIncome = payment.MonthlyIncome,
            };
            if (id == null || _context.Payments == null)
            {
                return NotFound();
            }

            if (payment == null)
            {
                return NotFound();
            }

            return View();
        }

        // POST: Payments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var payment = await _context.Payments.FindAsync(id);

            if (_context.Payments == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Payments'  is null.");
            }

            if (payment != null)
            {
                _context.Payments.Remove(payment);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PaymentExists(int id)
        {
            return (_context.Payments?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/TenantsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RentierApplication.DAL.Entities;
using RentierApplication.Data;
using RentierApplication.ViewModels;
using Exception = System.Exception;

namespace RentierApplication.Controllers
{
    public class TenantsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TenantsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ttirbute for this action

        [HttpGet]
        [Route("/tenants")]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Tenants.Include(t => t.RealEstateTenant);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Tenants/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Tenants == null)
            {
                return NotFound();
            }

            var tenants = await _context.Tenants

                .FirstOrDefaultAsync(tenant => tenant.ID == id);
            if (tenants == null)
            {
                return NotFound();
            }

            return View(tenants);
        }

        // GET: Tenants/Create
        public IActionResult Create()
        {
            ViewData["RealEstateID"] = new SelectList(_context.RealEstates, "ID", "Name");
            return View();
        }

        // POST: Tenants/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TenantCreateViewModel tenantToAdd)
        {
            var tenant = new Tenant()
            {
                Name = tenantToAdd.Name,
                Email = tenantToAdd.Email,
                Surname = tenantToAdd.Surname,
                MoneyObligation = 0,
                Surety = tenantToAdd.Surety,
                RealEstateID = tenantToAdd.RealEstateID,
            };

            if (ModelState.IsValid)
            {
                _context.Add(tenant);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["RealEstateID"] = new SelectList(_context.RealEstates, "ID", "Name", tenant.RealEstateID);
            return View((TenantCreateViewModel)tenantToAdd);
        }

        // ON GET TYLKO ID !!!
        // GET: Tenants/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Tenants == null)
            {
                return NotFound();
            }

            var tenants = await _context.Tenants.FindAsync(id);
            if (tenants == null)
            {
                return NotFound();
            }
            ViewData["RealEstateID"] = new SelectList(_context.RealEstates, "ID", "Name", tenants.RealEstateID);
            return View(tenants);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, TenantEditViewModel tenantToEdit)
        {
            var existingTenant = await _context.Tenants.FindAsync(id);
            if (existingTenant == null)
            {
                return NotFound();
            }
            existingTenant.Name = tenantToEdit.Name;
            existingTenant.Email = tenantToEdit.Email;
            existingTenant.Surname = tenantToEdit.Surname;
            existingTenant.MoneyObligation = tenantToEdit.MoneyObligation;
            existingTenant.Surety = tenantToEdit.Surety;
            existingTenant.RealEstateID = tenantToEdit.RealEstateID;

            if (id != tenantToEdit.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (Exception ex)
                {
                    return UnprocessableEntity(ex);
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RealEstateID"] = new SelectList(_context.RealEstates, "ID", "Name", tenantToEdit.RealEstateID);
            return View();
        }

        // GET: Tenants/Delete/5
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            var existingTenant = await _context.Tenants
                .Include(t => t.RealEstateTenant)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (existingTenant == null)
            {
                return NotFound();
            }

            TenantDeleteViewModel tenantToDelete = new TenantDeleteViewModel()
            {
                Surname = existingTenant.Surname,
                Name = existingTenant.Name,
                Email = existingTenant.Email,
                MoneyObligation = existingTenant.MoneyObligation,
                Surety = existingTenant.Surety,
                ID = existingTenant.ID
            };

            //return View(TenantDeleteViewModel tenantToDelete);
            return View(tenantToDelete);
        }

        // POST: Tenants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var existingTenant = await _context.Tenants
                .FirstOrDefaultAsync(m => m.ID == id);
            if (existingTenant == null)
            {
                return NotFound();
            }

            _context.Tenants.Remove(existingTenant);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/RealEstates/Create.cshtml
@model RentierApplication.DAL.Entities.RealEstate

@{
    ViewData["Title"] = "Create";
}

<h1>Enter name and desciption of new Real Estate respectively</h1>

<h4>RealEstate</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>         
          
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Real Estate List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/RealEstates/Delete.cshtml
@model RentierApplication.DAL.Entities.RealEstate

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RealEstate</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to Real Estate List</a>
    </form>
</div>

Views/RealEstates/Details.cshtml
@model RentierApplication.DAL.Entities.RealEstate

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
<h1>Real Estate menagement page: </h1>
<a href="@Url.Action("Index", "Payments")"> GO to finance of  Real Estate </a>
<div>
    <h4>RealEstate</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
        
    </dl>

        <div style="border-style:solid">
        @await Html.PartialAsync("~/Views/Tenants/Index.cshtml", Model.Tenants)
</div>  
    <button type="button" class="btn btn-light" onclick="location.href='@Url.Action("Index", "Tenants")'">Tenants</button>;

    




</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-action="Index">Back to Real Estate List</a>
</div>

Views/RealEstates/Edit.cshtml
@model RentierApplication.DAL.Entities.RealEstate

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>RealEstate</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Real Estate List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/RealEstates/Index.cshtml
@model IEnumerable<RentierApplication.DAL.Entities.RealEstate>

@{
    ViewData["Title"] = "Welcome";
}

<h1>Real Estate menagement page: </h1>
<a href="@Url.Action("Index", "Payments")">Real Estate Finance /Payment </a>
<p>
    <a asp-action="Create">Add new Real Estate...</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
             <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
               
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                @* <a asp-action="Details" asp-route-id="@item.ID">Details</a> |  *@
                    @Html.ActionLink("Link to Index action of Home controller with id=100500 and name='John Doe'",
                             "Details", "RealEstates",
                             new { realEstateID = item.ID})
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/RealEstates/Tenants.cshtml
@model IEnumerable<RentierApplication.Data.Entities.Tenants>

@{
    ViewData["Title"] = "Index";
    var id = ViewData["RealEstateID"];

}


<h1>Index</h1>

<p>
    
    <input type="button" value="Create new tenant" onclick="location.href='@Url.Action("Create", "Tenants", new{id=id})'" />
    
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MoneyObligation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Surety)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RealEstateTenant)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Surname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MoneyObligation)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Surety)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RealEstateTenant)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                   @* <a asp-action="DeleteTenantFromRealEstate" asp-route-id="@item.ID">Delete</a>*@
                    @Html.ActionLink("Delete", "DeleteTenantFromRealEstate", "RealEstates",new {realEstateID = item.RealEstateID, tenantID = item.ID})

                </td>
            </tr>
        }
    </tbody>
</table>